### ISSUE TITLE
Data Error

### ISSUE THREAD

**Issue by nicoforteza** [SimFin/simfin#12]
Hi,
Is it possible not to include the latest figures of the fundamental data for every published report? I mean, to not overwrite the original published figure with the restated figure. Otherwise, the whole fundamental data is biased! (survivorship and look-ahead bias is not being taken into account)
thank you very much,

Nico

**Comment by thf24** [comment]
This is already available via the "as reported" variants:

df = sf.load_income(variant='annual-asreported', market='us')

This a SimFin+ only feature.

More info here:
https://simfin.com/data/bulk?dataset=income&variant=annual-asreported&market=us
