### ISSUE TITLE
.csv files (as in legacy site)

### ISSUE THREAD

**Issue by teachscience** [SimFin/simfin#17]
Hello, 

My students and I for several years purchased .csv files of US annual data from simfin.com to analyze statistically.  Unfortunately we are having difficulties navigating the new website and locating these SimFin+ .csv files.  Can anyone point us in the right direction?

All the Best, 

Mr. Harrington

**Comment by thf24** [comment]
We just updated the website and this is now available here: https://app.simfin.com/bulk-download
