### ISSUE TITLE
Add "Cash from (Repurchase of) Equity"  to Data Finder

### ISSUE THREAD

**Issue by igyr22** [SimFin/simfin#5]
# Feature Suggestion

Could you add  "Cash from (Repurchase of) Equity"  to data finder  under Financial Statements (Cash Flow) dropdown box?  It is a very common   data value that could be added for SimFin+  paid users in data finder since it is found in bulk data already.  

## Description

The data finder is commonly used for those users that prefer this functionality over the API.  In order to obtain useful info the dropdown feature was added which is good.  It would be great if "Cash from (Repurchase of) Equity"  was added to the Financial Statements dropdown, under Cash flow.   

## Code

N/a

## Example

N/a

**Comment by thf24** [comment]
Hi, please use the forum to suggest such changes, this is only for the Python API (I'm adding it to the to-do list still).

**Comment by thf24** [comment]
Thanks for reporting this. It looks like there was a problem in the database for a company that was updated yesterday leading to duplicated values in the TTM files, it's fixed now. The bulk files are being updated now and then it should work again.
