### ISSUE TITLE
Constant CAPEX contains incorrect value

### ISSUE THREAD

**Issue by Mattias-NCVIB** [SimFin/simfin#6]
In https://github.com/SimFin/simfin/blob/master/simfin/names.py 

CAPEX = 'Capital Expenditures'

then, later

CAPEX = CHG_FIX_ASSETS_INT = 'Change in Fixed Assets & Intangibles'

Seems incorrect?

/mattias

**Comment by thf24** [comment]
Sorry I didn't see this before.

Most companies don't report directly "CAPEX only" but instead the net change, which is "Change in Fixed Assets & Intangibles", so this is the best approximation for CAPEX in order to not exclude too many companies from the calculations.

**Comment by thf24** [comment]
There is a separate field for CAPEX only that you can also use if you have a SimFin+ subscription, it's called "PURCH_FIX_ASSETS" for fixed assets and "ACQ_FIX_ASSETS_INT" for fixed assets + intangibles.
